// Code authored by Dean Edis (DeanTheCoder).
// Anyone is free to copy, modify, use, compile, or distribute this software,
// either in source code form or as a compiled binary, for any purpose.
// 
// If you modify the code, please retain this copyright header,
// and consider contributing back to the repository or letting us know
// about your modifications. Your contributions are valued!
// 
// THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND.

namespace ZXBasic.Basic;

public enum BasicKeyword : ushort
{
    Rnd = 165,
    InkeyString,
    Pi,
    Fn,
    Point,
    ScreenString,
    Attr,
    At,
    Tab,
    ValString,
    Code,
    Val,
    Len,
    Sin,
    Cos,
    Tan,
    Asn,
    Acs,
    Atn,
    Ln,
    Exp,
    Int,
    Sqr,
    Sgn,
    Abs,
    Peek,
    In,
    Usr,
    StrString,
    ChrString,
    Not,
    Bin,
    Or,
    And,
    LessThanOrEqual,
    GreaterThanOrEqual,
    NotEqual,
    Line,
    Then,
    To,
    Step,
    DefFn,
    Cat,
    Format,
    Move,
    Erase,
    OpenChannel,
    CloseChannel,
    Merge,
    Verify,
    Beep,
    Circle,
    Ink,
    Paper,
    Flash,
    Bright,
    Inverse,
    Over,
    Out,
    Lprint,
    Llist,
    Stop,
    Read,
    Data,
    Restore,
    New,
    Border,
    Continue,
    Dim,
    Rem,
    For,
    GoTo,
    GoSub,
    Input,
    Load,
    List,
    Let,
    Pause,
    Next,
    Poke,
    Print,
    Plot,
    Run,
    Save,
    Randomize,
    If,
    Cls,
    Draw,
    Clear,
    Return,
    Copy,
    Fill
}
